### ISSUE TITLE
Headers are missing cant build on Xcode 

### ISSUE THREAD

**Issue by easy-fw** [siuying/peerflix-ios#1]
'libavformat/avformat.h' file not found

all the lib headers are not found.

Thank you !!!

**Comment by siuying** [comment]
I missed something in the script that download the static library. Try to update the repo and run `bash ./bin/setup_ijkplayer` again https://github.com/siuying/peerflix-ios#building

**Comment by easy-fw** [comment]
The problem is that script  is downloading the libraries but, I think it is putting them in the wrong place so when compiling is not finding them.

**Comment by siuying** [comment]
I think the latest commit fixed that. Try to move the decompressed `build` folder to `ijkplayer/ios/`.

**Comment by easy-fw** [comment]
i moved the build folder and now i can get past that, now i am having another problem.

/peerflix-ios/node_modules: No such file or directory

thank you

**Comment by siuying** [comment]
you need to [install JXcore](https://github.com/siuying/peerflix-ios#building) and run `jx install`, which will install npm dependencies. You can put the `jx` in PATH, or just put it in peerflix-ios folder and run ./jx install.

**Comment by easy-fw** [comment]
thank you , now after i did jx install it creates the folder, compiles and install perfectly.

Now the problem is that search in not working somehow, i get this.

SetTemp wasn't registered

SetHost wasn't registered

But no search results.

**Comment by siuying** [comment]
I have not seen this error before, but I guess you can find `Peerflix/JXCore/JXcore+Extension.swift`, and move 

```
        JXcore.callEventCallback("SetTemp", withParams: [temp])
        JXcore.callEventCallback("SetHost", withParams: [NetHelper.getWifiAddress()])
```

above

```
JXcore.callEventCallback("StartApplication", withParams: ["./js/app.js"])
```

so that it looks like:

```
        JXcore.callEventCallback("SetTemp", withParams: [temp])
        JXcore.callEventCallback("SetHost", withParams: [NetHelper.getWifiAddress()])

        JXcore.callEventCallback("StartApplication", withParams: ["./js/app.js"])

        App.prepareTemporaryDirectory()
        let temp = App.temporaryDirectory()

```

This should make sure the callbacks setup before the program use it.

**Comment by easy-fw** [comment]
**this is when i start the application**

Initializing JXcore engine
JXcore engine is ready
Starting JXcore engine
JXcore engine is started
SetTemp wasn't registered

SetHost wasn't registered

**This is when i select kisckass for example:**

loadMainFile Error /var/mobile/Containers/Bundle/Application/EFBECD1B-4716-4E67-B684-55879564CC26/Peerflix.app/js/app.js Please copy ./app/browser/constant/APIKeys.detault.js to ./app/browser/constant/APIKeys.js and set all services API keys!

**Comment by siuying** [comment]
The "API keys!" message is not related, as the app have not actually use those api yet. Try to follow what I mentioned above, if that didnt solve the problem, you'll have to figure it out as I cant replicate it.

**Comment by easy-fw** [comment]
I did that above but still the same.
Anyway thank you very much, if i find a solution to my problem i will post it here.

Regards.

**Comment by AdamGoodApp** [comment]
Have the same problem with the search not working.

**Comment by siuying** [comment]
I found that the real cause is I throw error when the API key is not set. I have fixed that. Please try to fetch the latest code and try again!

**Comment by siuying** [comment]
Fix this for I believe the issue has been resolved. if not, please open a new issue.

**Comment by FyhSky** [comment]
Have the same problem ：
Please copy ./app/browser/constant/APIKeys.detault.js to ./app/browser/constant/APIKeys.js and set all services API keys!

and search no  result.
