### ISSUE TITLE
Update building instructions

### ISSUE THREAD

**Issue by vahotm** [siuying/peerflix-ios#2]
Instructions are not clear and links are not working.
[http://jxcore.com/downloads/](http://jxcore.com/downloads/) redirects to [https://github.com/jxcore/jxcore/downloads/](https://github.com/jxcore/jxcore/downloads/) and is empty directory.
[http://nightlies.videolan.org/build/ios/last](http://nightlies.videolan.org/build/ios/last) in setup_vlc script is not working.

**Comment by siuying** [comment]
Time has change and the dependency has changed.

1. you may refer https://github.com/jxcore/jxcore/ to how to build jxcore
2. it seems they moved the binaries to http://nightlies.videolan.org/build/iOS/last/

Unfortunately I do not have time to guide you compile this project, you would really have to figure it out yourself.
